name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag the Docker image
        run: |
          docker build -t bookbigpw/recipe:latest .
      
      - name: Push Docker image to registry
        run: docker push bookbigpw/recipe:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull bookbigpw/recipe:latest
            docker stop your-app-container || true
            docker rm your-app-container || true
            docker run -d --name your-app-container -p 80:80 bookbigpw/recipe:latest
